---
- hosts: static_page

  vars:
    packages:
      - git
      - apache2

  tasks:
    - name: Ensure packages installed
      sudo: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Git clone remote static page repo
      sudo: yes
      git:
        repo=https://github.com/Yaowenjie/static_page.git
        dest=/home/var/www/static_page
        update=yes

    - name: Enabled apache2 mod_rewrite
      sudo: yes
      apache2_module:
        name: rewrite
        state: present

    - name: Start apache2 service
      sudo: yes
      service:
        name: apache2
        state: restarted