---
- hosts: static_page

  vars:
    packages:
      - git
      - apache2

  tasks:
    - name: Ensure packages installed
      sudo: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"