---
- hosts: static_page
  tasks:
    - name: Ensure git installed
      sudo: yes
      apt:
        name: git
        state: present

    - name: Ensure apache2 installed
      sudo: yes
      apt:
          name: apache2
          state: present
